type Session {
  sessionId: String!
  game: Game!
  name: String!
}

type Game {
  psychic: String
  guesser: String
  state: String!
  leftStatement: String
  rightStatement: String
  psychicSubject: String
  psychicScore: Int
  guessedScore: Int
  sessions: [Session!] @relation
}

type Query {
  games: [Game]
}
